# Generated by Django 3.2.4 on 2022-06-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='project-default.png', null=True, upload_to=''),
        ),
    ]
